---
# Initial system setup. Requires root access to the system

- hosts: all

  become: true

  tasks:

    - name: Ensure root group {{ root_group }}
      group:
        name: "{{ root_group }}"
        state: present

    - name: Allow root group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%{{ root_group }}"
        line: "{{ admin_user_name }} ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"

    - name: Create {{ admin_user_name }} user with sudo privileges
      user:
        name: "{{ admin_user_name }}"
        groups: "{{ root_group }}"

    - name: Setup ssh authorized key for {{ admin_user_name }} user
      authorized_key:
        user: "{{ admin_user_name }}"
        state: present
        key: "{{ item }}"
      with_file:
        - "{{ public_key_file }}"
